apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-mutating-webhook
  labels:
    app: pod-mutating-webhook
webhooks:
- name: pod-mutating-webhook.default.svc.cluster.local
  clientConfig:
    service:
      name: pod-mutating-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate
      port: 443
    caBundle: {{ .Values.tls.crt | b64enc }}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - ""
    apiVersions:
    - v1
    resources:
    - pods
  sideEffects: None
  timeoutSeconds: 5
  reinvocationPolicy: Never
  failurePolicy: Ignore
  namespaceSelector:
    matchLabels:
      pod-mutating-webhook: enabled
